### ISSUE TITLE
Change how the device list is handled.

### ISSUE THREAD

**Issue by gfabbris** [APS-4ID-POLAR/polar_instrument#58]
It'd be useful to have a dictionary that looked more like: `devices_list = dict(eiger4id = dict(module="ad_eiger1M", baseline=False, ...))`. This way we could have a "load_device" function where the user just needed to give the name and it'd load it.

This essentially means that the .yml files would need to be "inverted", from:
```yml
ad_eiger1M:
  device: eiger1m
  baseline: False
```
to:
```yml
eiger1m:
  module: ad_eiger1M
  baseline: False
```

**Comment by prjemian** [comment]
Such as [this](https://github.com/BCDA-APS/bs_model_instrument/blob/68c5869a01aaa116e53a7e262ca5a07a09a752c3/src/instrument/configs/devices.yml)?

```yaml
# Guarneri-style device YAML configuration

apstools.devices.SimulatedApsPssShutterWithStatus:
- name: shutter
  labels: ["shutters"]

# ophyd.Signal:
# - name: test
#   value: 50.7
# - name: t2
#   value: 2

# apstools.synApps.Optics2Slit2D_HV:
# - name: slit1
#   prefix: ioc:Slit1
#   labels: ["slits"]

# hkl.SimulatedE4CV:
# - name: sim4c
#   prefix: ""
#   labels: ["diffractometer"]

# ophyd.scaler.ScalerCH:
# - name: scaler1
#   prefix: vme:scaler1
#   labels: ["scalers", "detectors"]

# ophyd.EpicsMotor:
# - {name: m1, prefix: gp:m1, labels: ["motor"]}
# - {name: m2, prefix: gp:m2, labels: ["motor"]}
# - {name: m3, prefix: gp:m3, labels: ["motor"]}
# - {name: m4, prefix: gp:m4, labels: ["motor"]}
```

[`RE(make_devices())`](https://github.com/BCDA-APS/bs_model_instrument/blob/68c5869a01aaa116e53a7e262ca5a07a09a752c3/src/instrument/utils/make_devices_yaml.py) is used to (re)create the ophyd-style devices from the YAML file. 

With such definitions, an [ophyd registry](https://github.com/spc-group/ophyd-registry/tree/main) is used by a plan (or stub) to get the device object: `dx = oregistry["motor127"]`

**Comment by prjemian** [comment]
The `oregistry` would replace the `devices_list` (a `dict`, actually) shown above.

**Comment by prjemian** [comment]
The `yaml` file format makes it easy to use standard devices, as long as there are kwargs for all the parts you need to specify.

You only need to write local Python code in `instrument/devices` for those classes that need custom handling. Motors, slits, shutters all have standard kwargs. The apstools package has an area detector factory that can be used.  Diffractometers need custom code to assign motor channels.  See this section of the (quite new) docs.

**Comment by prjemian** [comment]
https://bcda-aps.github.io/bs_model_instrument/api/devices.html#diffractometers

**Comment by prjemian** [comment]
[Guarneri](https://github.com/spc-group/guarneri) provides the code that creates the ophyd objects from the configuration file.  The `bs_model_instrument` has an [addition](https://github.com/BCDA-APS/bs_model_instrument/blob/68c5869a01aaa116e53a7e262ca5a07a09a752c3/src/instrument/utils/make_devices_yaml.py#L98) to allow the configuration files to be written with YAML.  The YAML format makes description of motors (and other objects that share constructor code) concise:

```yaml
ophyd.EpicsMotor:
- {name: m1, prefix: ioc:m1, labels: ["motor"]}
- {name: m2, prefix: ioc:m2, labels: ["motor"]}
- {name: m3, prefix: ioc:m3, labels: ["motor"]}
- {name: dx, prefix: vme:m58:c0:m1, labels: ["motor"]}
- {name: dy, prefix: vme:m58:c0:m2, labels: ["motor"]}
```

**Comment by gfabbris** [comment]
We have something similar (like [this](https://github.com/APS-4ID-POLAR/polar_instrument/blob/main/src/instrument/configs/4ida_devices.yml)), but instead of passing all the arguments, we import the device from the file (where it already has all the parameters). But I think it's a good idea to have the arguments in the yml file.

But we load it all during startup using `locals()`. https://github.com/APS-4ID-POLAR/polar_instrument/blob/dc5fc7eb3b430de246b50adddea6c04aeb2f4c2c/src/instrument/devices/__init__.py#L47

But in any case, I'm considering cases where the device was not setup during startup (maybe it was off), and now the user wants to load it. For this, I'm wondering if it's better to have the items in the yml reversed, something like:
```python:
shutter:
 - name: apstools.devices.SimulatedApsPssShutterWithStatus
   labels: ["shutters"]
```
It will have the disadvantage that each device would probably need an entry. But it may make the .yml a bit easier to follow, and easier to parse it into something like a dictionary that could be more easily used by the user to load a device after bluesky started.

**Comment by prjemian** [comment]
Current philosophy in `bs_model_instrument` is *everything is a plan or plan stub*.  Reduces user confusion about how to write Python code for bluesky (command-line use *vs.* `RE()` use).  Also enables easier use of queue-server.  Device setup code becomes a plan stub (plan that does not generate a `run`).  A master setup can call all the requisite plan stubs for the occasion.  Or, as you point out, setup for a device can be repeated as needed.

Having all the devices described in the YAML file also provides the user some clarity about what devices are provided.

**Comment by prjemian** [comment]
We tried that.  It's nice that YAML enforces all objects to have unique names.  This code is indirect about the `name` and this will require re-explaining to new users.  The standard ophyd device construction is: ``callable(prefix="", name="", **kwargs)`.  The YAML we adopted uses this form:

```yaml
callable:
  - prefix: ""
  - name: ""
```

Other kwargs would follow.  We (via the `guarneri` package) treat `prefix` as a kwarg.  There are no `*args`.  Unspecified kwargs get their default values.  (We'll need to adjust some device classes in apstools for this.)

**Comment by prjemian** [comment]
A rewrite of the `bs_model_instrument.instrument.utils.make_devices_yaml.Instrument` class could use the inverted form:

```yaml
name:
  - callable: callable
  - name: ""
  - prefix: ""
```

File will begin to look quite long when dozens of motors are specified this way.

**Comment by prjemian** [comment]
That is:

```yaml
shutter:
 - callable: apstools.devices.SimulatedApsPssShutterWithStatus
   labels: ["shutters"]
```
